### PR TITLE
zero division error

### LINKED ISSUE #41: ZeroDivisionError: float division by zero
Scrolling an EPUB may cause traceback;

```log
Traceback (most recent call last):
  File "/usr/share/sugar/activities/Read.activity/epubview/epubview.py", line 369, in _view_scrolled_cb
    scrollfactor = scrollval / (scroll_upper - scroll_page_size)
ZeroDivisionError: float division by zero
```

### PR DESCRIPTION
**Pull request by ayushnawal**
Fixes #41

### CODE REVIEW

**Comment by srevinsaju** [comment]
Reviewed. Ready to merge

**Comment by quozl** [comment]
Thanks.  Reviewed.  This is a Fructose activity and we apply tighter review.  Your commit message was a bit brief.  Please explain how to reproduce the problem and why it happened?  See [Making commits](https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#making-commits).

**Comment by ayushnawal** [comment]
Reproduced the problem as stated in #41 by scrolling EPUB, suddenly it appeared in logs.

It happened because of the denominator in line 369 of `epubview.py`, in cases when `(scroll_upper - scroll_page_size)` becomes zero it will give a zero division error because of no exception handling there. 

Sorry for making commit messages brief, a bad habit of mine, will try to make commit messages as descriptive as possible from now onwards.

**Comment by quozl** [comment]
You could amend your commit and edit the commit message, but I'll do it for you by using GitHub to write one.

**Pull request merged**
