### PR TITLE
Update release notes.

### PR DESCRIPTION
**Pull request by jdsimmons**
Updated release notes to describe the bug fix I did.

### CODE REVIEW

**Comment by quozl** [comment]
Your previous commit has joined the pull request; please rebase your branch and push, thanks.

**Comment by jdsimmons** [comment]
James,

I did a rebase using the fix_evince branch and pushed. I think I did this
correctly. Not sure what to look for.

James Simmons

**Comment by jdsimmons** [comment]
I have no idea what to do here. It looks like the previous commit is still showing up no matter what I try.

**Comment by jdsimmons** [comment]
Ibiam,

I think I did that locally. I did a rebase where I chose the fix_evince_bug
branch as the new base. The screen grab shows the result in Eclipse IDE. *But
the push I do afterwards seems to have no effect whatever*. The pull
request shows all three commits:

https://github.com/sugarlabs/read-activity/pull/47

James Simmons

**Comment by quozl** [comment]
When pushing after rebase, you will have to add the --force option, which if you are using an IDE may be an additional checkbox in the dialog or a variant of the push option in the menus.  If you can't get that to work, make a new branch from your rebased branch and push that, then open a new pull request.  It isn't the best workaround, as it makes life harder for your audience, but until you figure it out we can cope.  :grin:

**Comment by jdsimmons** [comment]
I gave up on rebase. I closed the other pull request and created a new one
containing the one file that needs updating.

Thanks.

James Simmons

**Pull request closed without merging**
