### PR TITLE
Add feature of inverted colors for EvinceViewer

### LINKED ISSUE #34: Add dark mode for PDFs
Evince has an _Inverted Colours_ toggle in the _File options_ with a shortcut of <kbd>ctrl</kbd>+<kbd>i</kbd>.  Add the same shortcut to invert colours when viewing a PDF with Read.

### PR DESCRIPTION
**Pull request by nswarup14**
Fixes #34 

**Issues**
1) I have not added an icon for the invert toggle button. I am a bad designer and I could not find suitable icons online
2) The invert color button can be clicked even when no PDF is loaded. Its behaviour is similar to that of the favourite button. However, it should be such that only when a PDF is loaded, can the button be clicked.

Kindly guide me on how I can proceed with the above two issues.

Tested on Sugar v0.114 and Ubuntu 18.04

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.  Good start.

**Code Review**

Rather than `import evinceadaptor` and `isinstance`, check for `set_inverted_colors` using `hasattr`.

**Function**

Minimum is to add the shortcut.

I don't think a button is needed, but if there's room on the toolbar then go ahead.  The button should be shown only when a PDF is displayed.

Without a button, a shortcut would go in the _key-press_ event handler.

**Icon**

For the Terminal activity, there are two [icons](https://github.com/sugarlabs/terminal-activity/tree/master/icons); `light-theme.svg` and `dark-theme.svg`.

**Comment by nswarup14** [comment]
@quozl 
I have added the shortcut. Now the button is displayed only if a PDF is loaded. The shortcut also works only if a PDF is loaded.

**Issues**
1) I had added the icons, `dark-theme.svg` and `light-theme.svg` to the `icons/` directory. However, on running the activity, the icons aren't getting displayed. Have I put the icons in the wrong folder?

Thanks

**Comment by quozl** [comment]
Thanks.  Reviewed as commits pushed to your branch.  Please review the commits and test.

The icons work fine for me.

**Comment by quozl** [comment]
p.s. you might be interested in the Wikipedia article [Technical Debt](https://en.wikipedia.org/wiki/Technical_debt).

**Comment by nswarup14** [comment]
@quozl 
Reviewed till https://github.com/sugarlabs/read-activity/pull/38/commits/2e88b6c76f82bb860044301bf9e6d0c2aac9d658.
I agree with the changes. I should have considered placing the button in the viewtoolbar earlier.

I shall be more rigorous from next time :smile: 
Thanks.

**Comment by quozl** [comment]
Changes in the rebase before merge were;
* switch from Terminal shortcut ctrl+shift+i to Evince shortcut ctrl+i,
* wrap the tooltips for translation, and added them to POT file,
* change the tooltips to be "Inverted Colors" and "Normal Colors" rather than theme,
* remove a blank line,

**Pull request merged**
