### PR TITLE
Add support for Beautiful Soup 4

### PR DESCRIPTION
**Pull request by City-busz**
It's a replacement for Beautiful Soup 3, which has no further development.

### CODE REVIEW

**Comment by City-busz** [comment]
Now I modified my patch to work with the older version too. Porting to HTMLParser would be too difficult for me.

**Comment by quozl** [comment]
Okay, I'll look at porting to HTMLParser.

What is your test method?  Searching inside an epub file, right?

Notes for myself; `SearchThread` called from `epubview.jobs._JobFind`, which is aliased as `epubview.JobFind`, which is called from `epubadapter.JobFind`, which is called from `EpubViewer.setup_find_job`, which is called by the toolbar `_search_find_first`.

I've also looked at packing bs4 inside the activity, which is something bs4 upstream [mention](https://www.crummy.com/software/BeautifulSoup/#Download); and is done in [InfoSlicer](https://github.com/sugarlabs/infoslicer/blob/master/infoslicer/processing/BeautifulSoup.py).

**Comment by quozl** [comment]
@City-busz, please review and test https://github.com/sugarlabs/read-activity/commit/a55a0cc6d70215ccb0d887df81555ef9edb09732 and let me know how it goes.

HTMLParser was not a good solution.

**Comment by City-busz** [comment]
I can't test it, because I unable to open any PDF or EPUB files. Here is the log:

```
** (sugar-activity:1856): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-XzBz0wGWEx: Kapcsolat elutasítva
/usr/lib/python2.7/site-packages/sugar3/activity/activity.py:96: PyGIWarning: SugarExt was imported without specifying a version first. Use gi.require_version('SugarExt', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import SugarExt

(sugar-activity:1856): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:16:32: The style property GtkExpander:expander-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(sugar-activity:1856): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:17:35: The style property GtkExpander:expander-spacing is deprecated and shouldn't be used anymore. It will be removed in a future version
1498748584.647367 WARNING root: Telepathy Account dbus.ObjectPath('/org/freedesktop/Telepathy/Account/salut/local_xmpp/account0') does not support Sugar collaboration
1498748584.861702 ERROR root: Showing empty Panel
/usr/lib/python2.7/site-packages/sugar3/datastore/datastore.py:100: UnicodeWarning: Unicode unequal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if key not in self._properties or self._properties[key] != value:
1498748728.266177 ERROR read-activity: Can not load document: ev-document-error-quark: A(z) elektronikus könyvdokumentum fájltípus (application/epub+zip) nem támogatott (0)
1498748728.269714 ERROR root: Calculate hash 84867dd77ed34d3ee04083bc7253142a
Traceback (most recent call last):
  File "/usr/share/sugar/activities/Read.activity/readactivity.py", line 679, in _show_journal_object_picker_cb
    self.read_file(jobject.file_path)
  File "/usr/share/sugar/activities/Read.activity/readactivity.py", line 732, in read_file
    self._load_document('file://' + tempfile)
  File "/usr/share/sugar/activities/Read.activity/readactivity.py", line 1038, in _load_document
    self._update_toc()
  File "/usr/share/sugar/activities/Read.activity/readactivity.py", line 612, in _update_toc
    if self._view.update_toc(self):
  File "/usr/share/sugar/activities/Read.activity/evinceadapter.py", line 277, in update_toc
    doc = self._model.get_document()
AttributeError: EvinceViewer instance has no attribute '_model'
1498748737.851733 ERROR read-activity: write_file(): EvinceViewer instance has no attribute '_model'
```
Package versions:
- gtk3 3.22.16
- sugar-toolkit-gtk3 0.110.0
- evince 3.24.0

Distribution: Arch Linux

And WebKit 3.0 is no longer available on Arch Linux, so the epubview needs to be ported to Webkit2 4.0.

**Comment by quozl** [comment]
Thanks.  No problem in my tests with PDF viewing on Ubuntu 17.10, using Evince 3.24.0, GTK+ 3.22.15 and Sugar Toolkit 0.110.  Port to WebKit2 is needed, raised as https://github.com/sugarlabs/read-activity/issues/17

**Comment by City-busz** [comment]
Okay. I'll check it later again once the WebKit2 port is finished.

**Comment by quozl** [comment]
I don't expect a WebKit2 port to happen any time soon; nobody yet willing to do it.  But you did raise the Beatiful Soup 3 dependency, which is now removed, so that's some progress.  Please do propose other changes as you get time.

**Pull request closed without merging**
